name: CI_build

on: [push, pull_request, workflow_dispatch]

jobs:
  
  filter_commit:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Start XML validation
      run: |
        $allowMaster = $true
        
        $isPush = ("${{github.event_name }}" -eq "push") ? $true : $false
        $isPull = !$isPush

        echo $isPush
        echo $isPull

        if ($allowMaster -or $isPush) {


        

        }
        else{
          Write-Output "Run standard process without commit filtration"
        }

      
        #echo "Hellow World"
        #throw "Changed files on this commit require full build."

  windows:
    needs: filter_commit
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Start widnow job
      run: |
        echo "Hellow World"

  gcc:
    needs: filter_commit
    runs-on: windows-latest

    steps:
    - name: Start gcc job
      uses: actions/checkout@v4
    - name: Start XML validation
      run: |
        echo "Hellow World"
